version: "3.8"

services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=clerk
      - APP_DB_PASS=king-in-the-castle
      - APP_DB_NAME=cinema_booking_system
      - APP_SCHEMA_NAME=cinema_booking_system
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 5433:5432
    volumes:
#      - ./db/:/var/lib/postgresql/data/
      - postgres-data:/var/lib/postgresql/data/
      - ./docker/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  cinema-booking:
    image: cinema-booking-system
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
volumes:
  postgres-data:
    driver: local
    name: postgres-data
